version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on: 
      - db       
    networks:
      - node-network

  db:
    image: mysql:5.7               
    command: --innodb-use-native-aio=0   
    container_name: db 
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: dilean123
    networks:
      - node-network      

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app  
    networks:
      - node-network      

networks:
  node-network:
    driver: bridge